version: "3.8"
services:
  db:
    container_name: database
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: passwort
      POSTGRES_DB: db-name
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data


volumes:
  db-data:
